name: Code Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install xmllint (libxml2-utils)
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Install ReportGenerator tool
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Add .NET tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Convert to Cobertura format
        run: |
          reportgenerator \
            -reports:"**/coverage.cobertura.xml" \
            -targetdir:"coverlet/reports" \
            -reporttypes:Cobertura

      - name: Validate code coverage
        run: |
          minCoverage=70
          coverageReportPath="coverlet/reports/Cobertura.xml"

          if [ ! -f "$coverageReportPath" ]; then
            echo "❌ Arquivo de cobertura não encontrado em $coverageReportPath"
            exit 1
          fi

          coveragePercentage=$(xmllint --xpath "string(//coverage/@line-rate)" "$coverageReportPath")
          coveragePercentagePerc=$(echo "$coveragePercentage * 100" | bc)

          coverageInt=$(printf "%.0f" "$coveragePercentagePerc")

          if [ "$coverageInt" -lt "$minCoverage" ]; then
            echo "❌ Cobertura de código ${coveragePercentagePerc}% está abaixo de ${minCoverage}%"
            exit 1
          else
            echo "✅ Cobertura de código ${coveragePercentagePerc}% está acima de ${minCoverage}%"
          fi

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverlet/reports
